CREATE TABLE "RDB_LINK"
(
"INFO" BYTE,
"PROP" INT,
"FNODE" INT,
"TNODE" INT,
"FNODE_PREV" INT,
"FNODE_NEXT" INT,
"TNODE_PREV" INT,
"TNODE_NEXT" INT
) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "RDB_NODE"
(
"INFO" BYTE,
"PROP" INT,
"LINK" INT
) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "RDB_PROP"
(
"INFO" BYTE,
"KEY" INT,
"VALUE" BIGINT,
"NEXT" INT
) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "SYSDBA"."LTK"
(
"VALUE" VARCHAR(128)
) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "SYSDBA"."V"
(
"VALUE" VARCHAR(4000)
) STORAGE(ON "MAIN", CLUSTERBTR) ;

