CREATE TABLE "RDB_N"
(
"ID"   INT,
"INFO" BYTE,
"PROP" INT,
"LINK" INT
) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "RDB_L"
(
"ID"   INT,
"INFO" BYTE,
"PROP" INT,
"FNODE" INT,
"TNODE" INT,
"FNODE_PREV" INT,
"FNODE_NEXT" INT,
"TNODE_PREV" INT,
"TNODE_NEXT" INT
) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "RDB_P"
(
"ID"   INT,
"INFO" BYTE,
"KEY" INT,
"VALUE" BIGINT,
"NEXT" INT
) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "RDB_V"
(
"ID"   INT,
"VALUE" VARCHAR(4000)
) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "RDB_LTK"
(
"ID"   INT,
"VALUE" VARCHAR(128)
) STORAGE(ON "MAIN", CLUSTERBTR) ;



